#!/bin/sh

PASS=true
ROOT=$PWD

cd $ROOT/fwends-frontend
JAVASCRIPT_FILES=$(git diff --cached --name-only --diff-filter=ACM src/ | grep ".jsx\{0,1\}$")
for FILE in $JAVASCRIPT_FILES
do
    npm run lint -- "$ROOT/$FILE"
    if [[ "$?" == 0 ]]; then
        echo "esLint passed: $FILE"
    else
        echo "esLint failed: $FILE"
        PASS=false
    fi
done

cd $ROOT/fwends-backend
GO_FILES=$(git diff --cached --name-only --diff-filter=ACM . | grep ".go$")
for FILE in $GO_FILES
do
    # dirname is used because a go file can use declarations from siblings
    # TODO: this causes double linting of some packages
    # TODO: this could lint files that aren't yet staged :/
    go vet $(dirname "$ROOT/$FILE")
    if [[ "$?" == 0 ]]; then
        echo "go vet passed: $FILE"
    else
        echo "go vet failed: $FILE"
        PASS=false
    fi
    staticcheck $(dirname "$ROOT/$FILE")
    if [[ "$?" == 0 ]]; then
        echo "go staticcheck passed: $FILE"
    else
        echo "go staticcheck failed: $FILE"
        PASS=false
    fi
done

cd $ROOT/fwends-test
PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACM . | grep ".py$")
for FILE in $PYTHON_FILES
do
    poetry run pylint "$ROOT/$FILE"
    if [[ "$?" == 0 ]]; then
        echo "pylint passed: $FILE"
    else
        echo "pylint failed: $FILE"
        PASS=false
    fi
done


if ! $PASS; then
    exit 1
else
    echo "Pre-commit checks passed"
fi
