#!/bin/sh

PASS=true
ROOT=$PWD

cd $ROOT/fwends-frontend
JAVASCRIPT_FILES=$(git diff --cached --name-only --diff-filter=ACM src/ | grep ".jsx\{0,1\}$")
for FILE in $JAVASCRIPT_FILES
do
    eslint "$ROOT/$FILE"
    if [[ "$?" == 0 ]]; then
        echo "ESLint passed: $FILE"
    else
        echo "ESLint failed: $FILE"
        PASS=false
    fi
done

cd $ROOT/fwends-backend
RUST_FILES=$(git diff --cached --name-only --diff-filter=ACM src/ | grep ".rs$")
if [[ $RUST_FILES ]]; then
    result=$(cargo fmt -- --check)
    echo "$result"
    if [[ -z $(cargo fmt -- --check) ]]; then
        echo "RustFmt fassed"
    else
        echo "RustFmt failed"
        PASS=false
    fi
fi

if ! $PASS; then
    exit 1
else
    echo "Pre-commit checks passed"
fi
