#!/bin/sh

PASS=true
ROOT=$PWD

cd $ROOT/fwends-frontend
JAVASCRIPT_FILES=$(git diff --cached --name-only --diff-filter=ACM src/ | grep ".jsx\{0,1\}$")
for FILE in $JAVASCRIPT_FILES
do
    eslint "$ROOT/$FILE"
    if [[ "$?" == 0 ]]; then
        echo "ESLint passed: $FILE"
    else
        echo "ESLint failed: $FILE"
        PASS=false
    fi
done

cd $ROOT/fwends-backend
GO_FILES=$(git diff --cached --name-only --diff-filter=ACM . | grep ".go$")
for FILE in $GO_FILES
do
    go vet "$ROOT/$FILE"
    if [[ "$?" == 0 ]]; then
        echo "Go vet passed: $FILE"
    else
        echo "Go vet failed: $FILE"
        PASS=false
    fi
    staticcheck "$ROOT/$FILE"
    if [[ "$?" == 0 ]]; then
        echo "Go staticcheck passed: $FILE"
    else
        echo "Go staticcheck failed: $FILE"
        PASS=false
    fi
done

if ! $PASS; then
    exit 1
else
    echo "Pre-commit checks passed"
fi
