apiVersion: v1
kind: Service
metadata:
  name: fwends-postgres
  labels:
    app: fwends-postgres
spec:
  ports:
  - port: 5432
    name: fwends-postgres
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fwends-postgres
spec:
  selector:
    matchLabels:
      app: fwends-postgres
  serviceName: fwends-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: fwends-postgres
    spec:
      containers:
      - name: fwends-postgres
        image: postgres
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: fwends-postgres
              key: superuserUser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fwends-postgres
              key: superuserPassword
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
