apiVersion: v1
kind: Service
metadata:
  name: fwends-nginx
  labels:
    app: fwends-nginx
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: fwends-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwends-nginx
  labels:
    app: fwends-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwends-nginx
  template:
    metadata:
      labels:
        app: fwends-nginx
    spec:
      containers:
        - name: fwends-nginx
          image: fwends-nginx
          ports:
            - containerPort: 80
              name: http
      initContainers:
        - name: init-backend
          image: alpine
          command: ['sh', '-c', "until nslookup fwends-backend.default.svc.cluster.local; do echo waiting for fwends-backend; sleep 2; done"]
        - name: init-minio
          image: alpine
          command: ['sh', '-c', "until nslookup fwends-minio.default.svc.cluster.local; do echo waiting for fwends-minio; sleep 2; done"]
