apiVersion: v1
kind: Service
metadata:
  name: fwends-nginx
  labels:
    app: fwends-nginx
spec:
  ports:
    - port: 80
      name: fwends-nginx
  selector:
    app: fwends-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwends-nginx
  labels:
    app: fwends-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwends-nginx
  template:
    metadata:
      labels:
        app: fwends-nginx
    spec:
      containers:
      - name: fwends-nginx
        image: fwends-nginx
        ports:
        - containerPort: 80
          name: http
