apiVersion: v1
kind: Service
metadata:
  name: fwends-backend
  labels:
    app: fwends-backend
spec:
  ports:
    - port: 80
      name: fwends-backend
  selector:
    app: fwends-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fwends-backend
  labels:
    app: fwends-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwends-backend
  template:
    metadata:
      labels:
        app: fwends-backend
    spec:
      containers:
      - name: fwends-backend
        image: fwends-backend
        ports:
        - containerPort: 80
          name: http
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: fwends-postgres
              key: host
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: fwends-postgres
              key: db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: fwends-postgres
              key: adminUser
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fwends-postgres
              key: adminPassword
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: fwends-redis
              key: host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fwends-redis
              key: password
        - name: OAUTH2_ENABLE
          valueFrom:
            configMapKeyRef:
              name: fwends-oauth2
              key: enable
        - name: OAUTH2_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: fwends-oauth2
              key: clientId
