apiVersion: v1
kind: Service
metadata:
  name: fwends-backend
  labels:
    app: fwends-backend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: fwends-backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fwends-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwends-backend
  serviceName: fwends-backend
  template:
    metadata:
      labels:
        app: fwends-backend
    spec:
      containers:
        - name: fwends-backend
          image: fwends-backend
          ports:
            - containerPort: 80
              name: http
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: fwends-postgres
                  key: host
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fwends-postgres
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: fwends-postgres
                  key: adminUser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fwends-postgres
                  key: adminPassword
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: fwends-redis
                  key: host
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fwends-redis
                  key: password
            - name: S3_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: fwends-s3
                  key: endpoint
            - name: S3_SSL_DISABLE
              valueFrom:
                configMapKeyRef:
                  name: fwends-s3
                  key: sslDisable
            - name: S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: fwends-s3
                  key: region
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fwends-s3
                  key: accessKey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: fwends-s3
                  key: secretKey
            - name: AUTH_ENABLE
              valueFrom:
                configMapKeyRef:
                  name: fwends-auth
                  key: enable
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: fwends-auth
                  key: googleClientId
