version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/usr/app/src
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/usr/app/src
  nginx: 
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
