apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
    - image: fwends-backend
      context: fwends-backend
    - image: fwends-frontend
      context: fwends-frontend
    - image: fwends-postgres
      context: fwends-postgres
deploy:
  kubectl:
    manifests:
      - kubernetes/*
