apiVersion: skaffold/v2beta26
kind: Config
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  local:
    concurrency: 4
  artifacts:
    - image: fwends-frontend
      context: fwends-frontend
      docker:
        buildArgs:
          WEBPACK_MODE: production
    - image: fwends-backend
      context: fwends-backend
    - image: fwends-postgres
      context: fwends-postgres
    - image: fwends-nginx
      context: fwends-nginx
      requires:
        - image: fwends-frontend
          alias: FRONTEND
deploy:
  kubectl:
    manifests:
      - kubernetes/*
profiles:
  - name: dev
    patches:
      - op: replace
        path: /build/artifacts/0/docker/buildArgs/WEBPACK_MODE
        value: development
  - name: import
    patches:
      - op: add
        path: /build/local/tryImportMissing
        value: true
portForward:
  - resourceType: service
    resourceName: fwends-nginx
    port: http
    address: 0.0.0.0
    localPort: 8080
