apiVersion: v1
kind: Secret
metadata:
  name: fwends-postgres
type: Opaque
data:
  adminUser: YWRtaW4=
  # TODO: replace with a secure password
  adminPassword: cG9zdGdyZXNwYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fwends-postgres
data:
  # TODO: replace if using external postgres
  host: fwends-postgres-0.fwends-postgres.default.svc.cluster.local
  db: fwends
