apiVersion: v1
kind: Secret
metadata:
  name: fwends-postgres
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  # TODO: replace with a secure password
  POSTGRES_PASSWORD: cG9zdGdyZXNwYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fwends-postgres
data:
  # TODO: replace if using external postgres
  POSTGRES_ENDPOINT: fwends-postgres.default.svc.cluster.local:5432
  POSTGRES_DB: fwends
  POSTGRES_SSL_MODE: disable
