apiVersion: v1
kind: Secret
metadata:
  name: fwends-redis
type: Opaque
data:
  # TODO: replace with a secure password
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fwends-redis
data:
  # TODO: replace if using external redis
  REDIS_ENDPOINT: fwends-redis.default.svc.cluster.local:6379
