apiVersion: v1
kind: Secret
metadata:
  name: fwends-s3
type: Opaque
data:
  # TODO: replace with a secure credentials
  S3_ACCESS_KEY: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  S3_SECRET_KEY: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fwends-s3
data:
  # TODO: replace if using a s3 compatible cloud storage service
  S3_ENDPOINT: http://fwends-minio.default.svc.cluster.local:9000
  S3_REGION: us-east-1
