apiVersion: v1
kind: Secret
metadata:
  name: fwends-postgres
type: Opaque
data:
  adminUser: YWRtaW4=
  adminPassword: cG9zdGdyZXNwYXNzd29yZA== # TODO: replace with a secure password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fwends-postgres
data:
  host: fwends-postgres # TODO: replace if using external postgres
  db: fwends
