apiVersion: v1
kind: Secret
metadata:
  name: fwends-s3
type: Opaque
data:
  # TODO: replace with a secure credentials
  accessKey: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=
  secretKey: d0phbHJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fwends-s3
data:
  # TODO: replace if using a s3 compatible cloud storage service
  endpoint: http://fwends-minio.default.svc.cluster.local:9000
  sslDisable: "true"
  region: us-east-1
