apiVersion: v1
kind: Secret
metadata:
  name: fwends-redis
type: Opaque
data:
  # TODO: replace with a secure password
  password: cmVkaXNwYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fwends-redis
data:
  # TODO: replace if using external redis
  host: fwends-redis.default.svc.cluster.local
