name: Docker Build and Push
inputs:
  registry: {}
  username: {}
  password: {}
  context: {}
  build-args: {}
  image: {}
  cache-tag: {}
  output-tag: {}
outputs:
  ref:
    value: ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.output-tag }}
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.output-tag }}
          ${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.cache-tag }}
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}:${{ inputs.cache-tag }}
        cache-to: type=inline
