name: Docker Build and Push
inputs:
  registry:
    required: true
  username:
    required: true
  password:
    required: true
  context:
    required: true
  build-args:
    required: false
  image:
    required: true
  cache-tag:
    required: true
  output-tag:
    required: true
outputs:
  ref:
    value: ${{ inputs.registry }}/${{ inputs.image }}/fwends-postgres:${{ inputs.sha }}
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ${{ inputs.context }}
        build-args: ${{ inputs.build-args }}
        push: true
        tags: |
          ${{ inputs.registry }}/${{ inputs.image }}/fwends-postgres:${{ inputs.output-tag }}
          ${{ inputs.registry }}/${{ inputs.image }}/fwends-postgres:${{ inputs.cache-tag }}
        cache-from: type=registry,ref=${{ inputs.registry }}/${{ inputs.image }}/fwends-postgres:${{ inputs.cache-tag }}
        cache-to: type=inline
