apiVersion: v1
kind: Service
metadata:
  name: fwends-backend
  labels:
    app: fwends-backend
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: fwends-backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fwends-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwends-backend
  serviceName: fwends-backend
  template:
    metadata:
      labels:
        app: fwends-backend
    spec:
      containers:
        - name: fwends-backend
          image: fwends-backend
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: fwends-auth
            - configMapRef:
                name: fwends-postgres
            - secretRef:
                name: fwends-postgres
            - configMapRef:
                name: fwends-redis
            - secretRef:
                name: fwends-redis
            - configMapRef:
                name: fwends-s3
            - secretRef:
                name: fwends-s3
