name: Continuous Integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Cache skaffold pipeline
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/cache
          key: commit-${{ github.sha }}
          restore-keys: |
            commit-
      - name: Build skaffold pipeline
        run: |
          skaffold build
      # TODO: find a way to cleanup skaffold orphan process
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Install pipenv
        run: |
          pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: fwends-test/Pipfile.lock
      - name: Install python dependencies
        working-directory: ./fwends-test
        run: |
          pipenv install
      - name: Start minikube cluster
        run: |
          minikube start
      # TODO: allow integration tests to poll, so this sleep isn't needed
      - name: Run skaffold pipeline
        run: |
          skaffold run --port-forward & \
          sleep 120
      - name: Run Integration tests
        working-directory: ./fwends-test
        run: |
          pipenv run pytest
      - name: Delete skaffold pipeline
        run: |
          skaffold delete
      - name: Delete minikube cluster
        run: |
          minikube delete
