name: Continuous Integration
on: [push]
jobs:
  fwends-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: fwends-frontend
          push: true
          tags: ghcr.io/${{github.repository}}/fwends-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  fwends-nginx:
    runs-on: ubuntu-latest
    needs: fwends-frontend 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: fwends-nginx
          build-args: |
            FRONTEND=ghcr.io/${{github.repository}}/fwends-frontend:${{ github.sha }}
          push: true
          tags: ghcr.io/${{github.repository}}/fwends-nginx:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  fwends-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: fwends-backend
          push: true
          tags: ghcr.io/${{github.repository}}/fwends-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  fwends-postgres:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: fwends-postgres
          push: true
          tags: ghcr.io/${{github.repository}}/fwends-postgres:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  fwends-redis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: fwends-redis
          push: true
          tags: ghcr.io/${{github.repository}}/fwends-redis:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  fwends-test:
    runs-on: ubuntu-latest
    needs: [fwends-backend,fwends-frontend,fwends-nginx,fwends-redis,fwends-postgres]
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Install pipenv
        run: |
          pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: fwends-test/Pipfile.lock
      - name: Install python dependencies
        working-directory: ./fwends-test
        run: |
          pipenv install
      - name: Start minikube cluster
        run: |
          minikube start
      # TODO: allow integration tests to poll, so this sleep isn't needed
      - name: Run skaffold pipeline
        run: |
          skaffold run --port-forward & \
          sleep 120
      - name: Run Integration tests
        working-directory: ./fwends-test
        run: |
          pipenv run pytest
      - name: Delete skaffold pipeline
        run: |
          skaffold delete
      - name: Delete minikube cluster
        run: |
          minikube delete
      # TODO: find a way to cleanup skaffold orphan process
