name: Integration Tests
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && \
          sudo install skaffold /usr/local/bin/
      - name: Install pipenv
        run: |
          pipx install pipenv
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: fwends-test/Pipfile.lock
      - name: Install python dependencies
        working-directory: ./fwends-test
        run: |
          python -m pipenv install
      - name: Start minikube cluster
        run: |
          minikube start
      - name: Cache skaffold pipeline
        uses: actions/cache@v2
        with:
          path: ~/.skaffold/cache
          key: commit-${{ github.sha }}
          restore-keys: |
            commit-${{ github.sha }}
            commit-
      - name: Build skaffold pipeline
        run: |
          skaffold build --cache-artifacts=true --cache-file=~/.skaffold/cache
      - name: Run skaffold pipeline
        run: |
          skaffold run --port-forward &
      # TODO: allow integration tests to poll, so this sleep isn't needed
      - name: Sleep to allow containers to start
        run: |
          sleep 5
      - name: Run Integration tests
        working-directory: ./fwends-test
        run: |
          python -m pipenv run pytest
      - name: Delete skaffold pipeline
        run: |
          skaffold delete
      - name: Delete minikube cluster
        run: |
          minikube delete
      # TODO: find a way to cleanup skaffold orphan process
