name: Lint
on: [push]
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Cache go dependencies
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('./fwends-backend/go.sum') }}
      - name: Install go dependencies
        working-directory: ./fwends-backend
        run: |
          go install
      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Lint go files with go vet
        working-directory: ./fwends-backend
        run: |
          go vet ./...
      - name: Lint go files with staticcheck
        working-directory: ./fwends-backend
        run: |
          staticcheck ./...
  javascript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache nodejs dependencies
        uses: actions/cache@v2
        with:
          path: ./fwends-frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./fwends-frontend/package-lock.json') }}
      - name: Install nodejs dependencies
        working-directory: ./fwends-frontend
        run: npm install
      - name: Lint javascript files
        working-directory: ./fwends-frontend
        run: npm run lint
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pipenv
        run: |
          pipx install pipenv
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
          cache-dependency-path: fwends-test/Pipfile.lock
      - name: Install python dependencies
        working-directory: ./fwends-test
        run: |
          pipenv install --dev
      - name: Lint python files
        working-directory: ./fwends-test
        run: |
          pipenv run pylint $(find . -name "*.py")
