name: Linting
on: [push]
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install pylint
        run: |
          pip install pylint
      - name: Lint python files
        working-directory: ./fwends-test
        run: |
          python -m pylint $(find . -name "*.py")
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install staticcheck
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Lint go files
        working-directory: ./fwends-backend
        run: |
          staticcheck ./...
